name: Publish Package to npmjs
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: |
          # Get the latest published version
          latest_version=$(npm view <package-name> version)
          
          # Increase the version number
          new_version=$(node -p "require('semver').inc('$latest_version', 'patch')")
          
          # Update the package.json file
          npm version "$new_version"
          
          # Publish the new version
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}